### ISSUE TITLE
The hook on `addSkill` of item.nut won't properly work for grandchildren of item containing FatigueOnSkillUse. Need a more reliable way that will work with all descendants of item.nut

### ISSUE THREAD

**Issue by LordMidas** [Battle-Brothers-Legends/mod_MSU#82]
For context: the issue is that there are weapons which have FatigueOnSkillUse defined in them. In the `addSkill` function of weapon.nut, they add this value to the FatigueCost of the skill. However, they do this AFTER calling `this.item.addSkill` and the skill is added to the actor's skill_container in `this.item.addSkill`. This results in the issue that MSU saves the `baseValue` of the Fatigue Cost before the FatigueOnSkillUse is added to the skill's cost and hence as soon as skill_container update runs, the fatigue cost is reset.

```squirrel
// weapon.nut:
function addSkill( _skill )
{
	this.item.addSkill(_skill);

	if (_skill.isType(this.Const.SkillType.Active))
	{
		_skill.setFatigueCost(this.Math.max(0, _skill.getFatigueCostRaw() + this.m.FatigueOnSkillUse));
	}
}

//item.nut:
function addSkill( _skill )
{
	_skill.setItem(this);
	this.m.SkillPtrs.push(_skill);
	this.getContainer().getActor().getSkills().add(_skill, this.m.SkillPtrs.len());
}
```

Secondly, in order to expand modding capability we need to ensure that any item which may have FatigueOnSkillUse defined in it e.g. shields (also true for vanilla), should be able to work properly and save the proper Base Value of FatigueCost including this increased cost.

Our current implementation solves this, however, if someone creates an abstract child of item.nut and makes an abstract grandchild of that with FatigueOnSkillUse defined in that grandchild, then our hook will fail to save the correct value.

One solution could be to hook the `setFatigueCost` function of skill.nut and cause it to update the saved base value. Something like the following. The optional arg is there in case someone wants to set the Fatigue Cost without changing the base value. However, I think this **optional arg is probably unnecessary** as in that case the modder can simply use `this.m.FatigueCost = _f` instead. So, I think always forcing the baseValue to be updated in this function is most likely ok.
```squirrel
local setFatigueCost = o.setFatigueCost;
o.setFatigueCost <- function( _f, _updateBaseValue = true ) // we add an optional arg
{
	if (_updateBaseValue) this.setBaseValue("FatigueCost", _f);
	setFatigueCost(_f); // the original function doesn't have the optional arg	 
}
```
Or is there a better solution? What do you think?

**Comment by Enduriel** [comment]
Why shouldn't this just be converted to a hookDescendants hook? Wouldn't that fix all the issues?

**Comment by LordMidas** [comment]
> Why shouldn't this just be converted to a hookDescendants hook? Wouldn't that fix all the issues?

No because of recursion issues. In this particular case we absolutely do not want the functions to run more than once per item.

**Comment by Enduriel** [comment]
I have a dumb solution that I don't like but it's an alternative to consider and could possibly inspire better ideas. We hookDescendants the addSkill function and add a new member to the m table (something like setFatigueCounter). The hook looks something like this:
```squirrel
o.m.setFatigueCounter = 0
local addSkill = o.addSkill;
o.addSkill = function( _skill )
{
	this.m.setFatigueCounter += 1;
	addSkill(_skill);
	this.m.setFatigueCounter -= 1;
	if (this.m.setFatigueCounter == 0)
	{
		// set raw fatigue value
	}
}
```
Actually this solution has kinda grown on me and I don't think it's that dumb (the names suck though don't use these I have a really bad headache so just doing simple stuff).

Maybe this can be used as a more generic solution and then call the new m member recursionLevel or smtng idk.

**Comment by LordMidas** [comment]
Closed via my suggested implementation (without the optional arg).
