### ISSUE TITLE
Should we be overwriting vanilla skill_container events to use `callSkillsFunction`? What's the point of doing this?

### ISSUE THREAD

**Issue by LordMidas** [Battle-Brothers-Legends/mod_MSU#87]
Perhaps we leave vanilla events alone and only use this function for our own events?

**Comment by Enduriel** [comment]
Iirc there were some advantages to doing this specifically related to the setdirty stuff which we still haven't fixed full, if you don't want it comment it out for now but we'll have to take a look at it again at some point.

**Comment by LordMidas** [comment]
We decided to keep it as we have for now.
